
var template_language = {

  'attack': ["murder","death","bloodshed","no more"],

  'attackController': ["murder","death","bloodshed","no more"],

  'build': [
    "We work.",
    "To earn",
    "the right",
    "to work.",
    "To earn",
    "the right",
    "to work.",
    "To earn",
    "the right",
    "to work.",
    "To earn",
    "the right",
    "to work.",
    "To earn",
    "the right",
    "to give",
    "Ourselves",
    "the rights",
    "to buy",
    "Ourselves",
    "the right",
    "to live",
    "To earn",
    "the right",
    "to die.",
    "You should",
    "have read",
    "the fine",
    "print, my",
    "friend.",
    "Should have",
    "read the",
    "fine print",
    "You should",
    "have read",
    "the fine",
    "print, my",
    "friend.",
    "Should have",
    "read the",
    "fine print",
    "(Welcome to",
    "our little",
    "town! Why",
    "don’t you",
    "settle down?",
    "Here, just",
    "fill out",
    "the paperwork",
    "and you",
    "can look",
    "around We",
    "work and",
    "then we",
    "work and",
    "then we",
    "work and",
    "then we",
    "work And",
    "then we",
    "work and",
    "then we",
    "end up",
    "in the",
    "ground)",
    "(WORK WORK",
    "HURRY HURRY",
    "WORK WORK",
    "WORRY WORRY",
    "WORK WORK",
    "HURRY HURRY",
    "WORRY HURRY",
    "WORK WORK)",
    "You should",
    "have read",
    "the fine",
    "print, my",
    "friend.",
    "Should have",
    "read the",
    "fine print",
    "You should",
    "have read",
    "the fine",
    "print, my",
    "friend.",
    "Should have",
    "read the",
    "fine print"
  ],

  'claimController': ["thievery"],

  'dismantle': ["Bob","The","Breaker.","Can he","break it?","YES HE", "CAN!!!"],

  'drop': ["Ew","get","this","off","of","me"],

  'harvest': [
    "We work.",
    "To earn",
    "the right",
    "to work.",
    "To earn",
    "the right",
    "to work.",
    "To earn",
    "the right",
    "to work.",
    "To earn",
    "the right",
    "to work.",
    "To earn",
    "the right",
    "to give",
    "Ourselves",
    "the rights",
    "to buy",
    "Ourselves",
    "the right",
    "to live",
    "To earn",
    "the right",
    "to die.",
    "You should",
    "have read",
    "the fine",
    "print, my",
    "friend.",
    "Should have",
    "read the",
    "fine print",
    "You should",
    "have read",
    "the fine",
    "print, my",
    "friend.",
    "Should have",
    "read the",
    "fine print",
    "(Welcome to",
    "our little",
    "town! Why",
    "don’t you",
    "settle down?",
    "Here, just",
    "fill out",
    "the paperwork",
    "and you",
    "can look",
    "around We",
    "work and",
    "then we",
    "work and",
    "then we",
    "work and",
    "then we",
    "work And",
    "then we",
    "work and",
    "then we",
    "end up",
    "in the",
    "ground)",
    "(WORK WORK",
    "HURRY HURRY",
    "WORK WORK",
    "WORRY WORRY",
    "WORK WORK",
    "HURRY HURRY",
    "WORRY HURRY",
    "WORK WORK)",
    "You should",
    "have read",
    "the fine",
    "print, my",
    "friend.",
    "Should have",
    "read the",
    "fine print",
    "You should",
    "have read",
    "the fine",
    "print, my",
    "friend.",
    "Should have",
    "read the",
    "fine print"
],

  'heal': ["healing away","I don't","know","what to","heal","i'll","heal","anyway","In this","screeps","day"],

  'move': [],

  'pickup': ["ooooh","yummy","delicous","gimme that"],

  'rangedAttack': ["murder","death","bloodshed","no more"],

  'rangedHeal': ["healing away","I don't","know","what to","heal","i'll","heal","anyway","In this","screeps","day"],

  'rangedMassAttack': ["murder","death","bloodshed","no more"],

  'repair': ["healing away","I don't","know","what to","heal","i'll","heal","anyway","In this","screeps","day"],

  'reserveController': ["mine!"],

  'suicide': ["and","now","the","end","is","near"],

  'transfer': ["yours now","take it","now, take","go, take"],

  'upgradeController': [
    "Work it", "Make it", "Do it", "Makes us",
    "Harder", "Better", "Faster", "Stronger",
    "More than", "Hour", "Hour", "Never", 
    "Ever", "After", "Work is", "Over",
    "Work it", "Make it", "Do it", "Makes us",
    "Harder", "Better", "Faster", "Stronger",
    "Work it", "Harder", "Make it", "Better",
    "Do it", "Faster", "Makes us", "Stronger",
    "More than", "Ever", "Hour", "After",
    "Hour", "Work is", "Never", "Over",
    "Work it", "Harder", "Make it", "Better",
    "Do it", "Faster", "Makes us", "Stronger",
    "More than", "Ever", "Hour", "After",
    "Hour", "Work is", "Never", "Over",
    "Work it", "Harder", "Make it", "Better",
    "Do it", "Faster", "Makes us", "Stronger",
    "More than", "Ever", "Hour", "After",
    "Hour", "Work is", "Never", "Over",
    "Work it", "Harder", "Make it", "Better",
    "Do it", "Faster", "Makes us", "Stronger",
    "More than", "Ever", "Hour", "After",
    "Hour", "Work is", "Never", "Over",
    "Work it", "Harder", "Make it", "Better",
    "Do it", "Faster", "Makes us",
    "More than", "Ever", "Hour", "After",
    "Hour", "Work is", "Never", "Over",
    "Work it", "Harder", "Make it", "Better",
    "Do it", "Faster", "Makes us", "Stronger",
    "More than", "Ever", "Hour", "After",
    "Hour", "Work is", "Never", "Over",
    "Work it", "Harder", "Make it",
    "Do it", "Faster", "Makes us",
    "More than", "Ever", "Hour", "After",
    "Hour", "Work is", "Never", "Over",
    "Work it", "Harder", "Make it", "Better",
    "Do it", "Faster", "Makes us", "Strong",
    "More than", "Ever", "Hour", "After",
    "Hour", "Work is", "Never", "Over",
    "Work it", "Make it", "Better",
    "Do it", "Faster", "Makes us", "Stronger",
    "More than", "Ever", "Hour", "After",
    "Hour", "Work is", "Never", "Over",
    "Work it", "Make it", "Better",
    "Do it", "Faster", "Makes us", "Stronger",
    "More than", "Ever", "Hour", "After",
    "Hour", "Work is", "Never", "Over",
    "Work it", "Make it", "Better",
    "Do it", "Faster", "Makes us", "Stronger",
    "More than", "Ever", "Hour", "After",
    "Hour", "Work is", "Never", "Over",
    "Work it", "Harder", "Do it", "Faster",
    "More than", "Ever", "Hour",
    "Work is", "Never", "Over",
    "Work it", "Harder", "Make it", "Better",
    "Do it", "Faster", "Makes us", "Stronger",
    "More than", "Ever", "Hour", "After",
    "Hour", "Work is", "Never", "Over"
  ],

  'withdraw': ["gimme now"],

}

module.exports = template_language
